@echo off
REM This script replaces the current .env file with the new one generated by the AI.
REM It's a workaround for the AI not having direct permission to edit .env files.

if exist new.env (
    echo Replacing .env with new.env...
    move /Y new.env .env
    echo Done.
) else (
    echo new.env not found. No changes made.
) 